import Link from "next/link";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 style={{ fontSize: 14, fontWeight: 600, color: "#0F172A", marginBottom: 8 }}>{title}</h2>
      <div style={{ fontSize: 14, color: "#4B5563", lineHeight: 1.75, display: "flex", flexDirection: "column", gap: 8 }}>{children}</div>
    </section>
  );
}

function H3({ children }: { children: React.ReactNode }) {
  return (
    <h3 style={{ marginTop: 16, marginBottom: 4, fontSize: 11, fontWeight: 600, letterSpacing: "0.06em", textTransform: "uppercase", color: "#6B7280" }}>
      {children}
    </h3>
  );
}

export default function PrivacyPage() {
  return (
    <div style={{ minHeight: "100vh", background: "#F8FAFC", fontFamily: "var(--font-geist-sans), system-ui, sans-serif" }}>
      <div style={{ margin: "0 auto", maxWidth: 640, padding: "56px 32px 80px" }}>

        <Link
          href="/"
          style={{ display: "inline-flex", alignItems: "center", gap: 6, fontSize: 13, color: "#9CA3AF", textDecoration: "none", marginBottom: 32 }}
        >
          <svg viewBox="0 0 16 16" width="14" height="14" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M10 12L6 8l4-4" />
          </svg>
          Back
        </Link>

        <h1 style={{ fontSize: 28, fontWeight: 700, color: "#0F172A", letterSpacing: "-0.02em", marginBottom: 8 }}>
          Privacy Policy and Terms of Use
        </h1>
        <p style={{ fontSize: 12, color: "#9CA3AF", marginBottom: 12 }}>
          Effective date: April 24, 2026. Governing law: Province of Ontario, Canada.
        </p>
        <p style={{ fontSize: 13, color: "#6B7280", lineHeight: 1.7, marginBottom: 40 }}>
          By creating an account or using WhatYouAte (the "App"), you agree to these terms in full. If you do not agree, do not use the App.
        </p>

        {/* ── TERMS OF USE ─────────────────────────────────── */}
        <p style={{ fontSize: 10, fontWeight: 700, letterSpacing: "0.12em", textTransform: "uppercase", color: "#D1D5DB", marginBottom: 20 }}>
          Terms of Use
        </p>
        <div style={{ display: "flex", flexDirection: "column", gap: 28 }}>

          <Section title="1. Not Medical Advice">
            <p>WhatYouAte is a general wellness and food-logging tool. Nothing in the App, including nutrition estimates, nudges, insights, or any other output, constitutes medical advice, dietetic advice, clinical nutrition guidance, or a substitute for the advice of a qualified healthcare professional.</p>
            <p>All calorie and macronutrient estimates are generated by artificial intelligence and are approximations only. AI-generated content may be inaccurate, incomplete, biased, or not applicable to your specific circumstances. You should not rely on the App to diagnose, treat, manage, or prevent any health condition.</p>
            <p>If you have or suspect a health condition, dietary disorder, or medical concern, consult a qualified healthcare provider before making changes to your diet or lifestyle.</p>
          </Section>

          <Section title="2. Eating Disorders and Vulnerable Users">
            <p>WhatYouAte is not intended for use by individuals who have or are at risk of developing an eating disorder, including but not limited to anorexia nervosa, bulimia nervosa, binge eating disorder, or any other disordered eating pattern. If you have a history of or are currently experiencing an eating disorder, please consult a qualified healthcare professional before using this App.</p>
            <p>The App is not designed to encourage, support, or facilitate restrictive eating, extreme caloric deficits, or any behaviour that may be harmful to your physical or mental health. If you feel the App is negatively affecting your relationship with food, stop using it and seek professional support.</p>
            <p>If you or someone you know is struggling with an eating disorder, contact the National Eating Disorder Information Centre (NEDIC) at 1-866-633-4220 or visit nedic.ca.</p>
          </Section>

          <Section title="3. Assumption of Risk">
            <p>You acknowledge and accept that: (a) AI-generated nutrition data is an estimate and may be materially incorrect; (b) the App does not verify that any food is free from allergens, intolerances, or contraindications; dietary restrictions you enter are used for general context only and do not constitute an allergen safety guarantee; (c) the App does not account for your medications, medical conditions, or clinical history; and (d) any decisions you make regarding your diet, exercise, or health based on App outputs are made at your sole risk and discretion.</p>
            <p>By using the App you voluntarily assume all risks associated with reliance on the App and its outputs.</p>
          </Section>

          <Section title="4. Limitation of Liability">
            <p>To the fullest extent permitted by applicable law, WhatYouAte, its founders, operators, employees, contractors, and affiliated parties (collectively, "WhatYouAte") shall have no liability whatsoever arising from or in connection with your use of, or inability to use, the App, including any reliance on nutrition data, nudges, or insights generated by the App.</p>
            <p>Without limiting the foregoing, the total aggregate liability of WhatYouAte for any and all claims, losses, damages, costs, or expenses of any kind, whether arising in contract, tort (including negligence), strict liability, or otherwise, shall not exceed the greater of: (a) the amount you paid to WhatYouAte in the twelve (12) months immediately preceding the event giving rise to the claim; or (b) ten Canadian dollars (CAD $10.00).</p>
            <p>In no event shall WhatYouAte be liable for any indirect, incidental, consequential, special, punitive, or exemplary damages, including loss of data, personal injury, health-related harm, or economic loss, even if advised of the possibility of such damages.</p>
            <p>Some jurisdictions do not permit the exclusion or limitation of certain warranties or liabilities. In such jurisdictions, liability is limited to the minimum extent required by applicable law.</p>
          </Section>

          <Section title="5. Indemnification">
            <p>You agree to indemnify, defend, and hold harmless WhatYouAte and its founders, operators, employees, contractors, and affiliated parties from and against any and all claims, damages, losses, costs, and expenses (including reasonable legal fees) arising out of or relating to: (a) your use of or access to the App; (b) your violation of these terms; (c) your violation of any applicable law or regulation; or (d) any content you submit, post, or transmit through the App.</p>
          </Section>

          <Section title="6. No Warranties">
            <p>The App is provided on an "as is" and "as available" basis without warranties of any kind, express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, accuracy, or non-infringement. WhatYouAte does not warrant that the App will be error-free, uninterrupted, or free of harmful components. WhatYouAte does not guarantee the accuracy, completeness, or reliability of any AI-generated nutritional data, estimates, nudges, or insights.</p>
          </Section>

          <Section title="7. Eligibility">
            <p>You must be at least 13 years of age to use the App. By using the App you represent that you meet this requirement. Users between 13 and 18 should have parental or guardian consent before use. WhatYouAte does not knowingly collect personal information from children under 13. If we become aware that a child under 13 has provided personal information, we will take steps to delete it promptly.</p>
          </Section>

          <Section title="8. Acceptable Use">
            <p>You agree not to: (a) use the App for any unlawful purpose; (b) attempt to reverse-engineer, scrape, or interfere with the App or its infrastructure; (c) use any App output to train, fine-tune, or develop artificial intelligence or machine learning models; (d) share your account credentials with others; or (e) use the App in any manner that could harm WhatYouAte or other users.</p>
          </Section>

          <Section title="9. Intellectual Property">
            <p>The App and all content, features, design, trademarks, and technology within it are owned by or licensed to WhatYouAte and are protected by applicable intellectual property laws. You are granted a limited, non-exclusive, non-transferable, revocable licence to use the App solely for your personal, non-commercial purposes in accordance with these terms. No other rights are granted. You may not copy, modify, distribute, sell, or create derivative works from any part of the App without prior written consent.</p>
          </Section>

          <Section title="10. Subscriptions and Billing">
            <p>Paid subscriptions are billed in advance on a recurring basis through Apple's App Store. All billing, payment processing, and subscription management is handled by Apple and is subject to Apple's Terms of Service. You may cancel at any time through your device's App Store subscription settings. Cancellation takes effect at the end of the current billing period. Refunds are governed by Apple's refund policy and are not provided by WhatYouAte directly, except where required by applicable law.</p>
          </Section>

          <Section title="11. Termination">
            <p>WhatYouAte may suspend or terminate your access at any time for violation of these terms or for any other reason, with or without notice. You may terminate your account at any time using the "Delete account" option in your Profile.</p>
          </Section>

          <Section title="12. Governing Law and Jurisdiction">
            <p>These terms and any dispute arising from your use of the App shall be governed exclusively by the laws of Canada and the laws of the Province of Ontario applicable therein, without regard to conflicts of law principles. You irrevocably submit to the exclusive jurisdiction of the courts of the Province of Ontario for the resolution of any such dispute.</p>
            <p>If you access the App from outside Canada, you do so at your own initiative and are responsible for compliance with any applicable local laws. Nothing herein limits WhatYouAte's right to seek injunctive or equitable relief in any competent court.</p>
          </Section>

          <Section title="13. Severability">
            <p>If any provision of these terms is found to be unlawful, void, or unenforceable, that provision shall be deemed severable and shall not affect the validity or enforceability of the remaining provisions, which shall continue in full force and effect.</p>
          </Section>

          <Section title="14. Entire Agreement">
            <p>These terms, together with the Privacy Policy below, constitute the entire agreement between you and WhatYouAte with respect to your use of the App and supersede all prior agreements, representations, and understandings. No waiver of any term shall be deemed a further or continuing waiver of that or any other term.</p>
          </Section>

          <Section title="15. Changes to Terms">
            <p>WhatYouAte reserves the right to modify these terms at any time. Material changes will be communicated in the App. Continued use of the App after changes are posted constitutes acceptance of the revised terms.</p>
          </Section>

        </div>

        {/* ── PRIVACY POLICY ───────────────────────────────── */}
        <p style={{ fontSize: 10, fontWeight: 700, letterSpacing: "0.12em", textTransform: "uppercase", color: "#D1D5DB", marginTop: 56, marginBottom: 20 }}>
          Privacy Policy
        </p>
        <div style={{ display: "flex", flexDirection: "column", gap: 28 }}>

          <Section title="16. Information We Collect">
            <H3>Account information</H3>
            <p>When you create an account we collect your email address and, optionally, your first and last name.</p>
            <H3>Profile information</H3>
            <p>To generate personalized nutrition targets we collect optional profile data including age, sex, height, weight, goal direction, activity level, and dietary restrictions. You may skip or update any of these at any time.</p>
            <H3>Usage data</H3>
            <p>We collect food logs, meal photos (see below), workout logs, supplement entries, and in-app activity to power your insights and nudges.</p>
            <H3>Apple Health data</H3>
            <p>With your permission, we read steps and sleep data from Apple Health (HealthKit). This data is transmitted to our servers solely to personalize your AI coach check-in. It is read at the time your daily message is generated and is not stored independently on our servers.</p>
            <H3>Push notification tokens</H3>
            <p>We store a push notification token for your device to deliver your daily AI coach check-in and reminders. You can disable notifications at any time in your device settings.</p>
            <H3>Device and technical data</H3>
            <p>We may collect basic technical information such as device type, operating system version, and crash logs solely for the purpose of maintaining app stability.</p>
          </Section>

          <Section title="17. Meal Photos">
            <p>Photos you capture are transmitted over an encrypted connection to our AI analysis providers (Anthropic and/or OpenAI) for the purpose of identifying food items and estimating nutritional content. Original full-resolution photos are not retained after analysis is complete. A compressed thumbnail is stored in our database linked to your food log entry for display purposes and is deleted when you delete the associated meal or your account.</p>
          </Section>

          <Section title="18. How We Use Your Information">
            <p>We use your information to: (a) operate and improve the App; (b) generate personalized nutrition estimates, nudges, and insights; (c) calculate progress toward your stated health goals; (d) process subscription payments; (e) send you service-related and occasional product communications via email or push notification; and (f) comply with legal obligations.</p>
            <p>We do not sell your personal information to third parties. We do not use your personal information for third-party advertising purposes.</p>
          </Section>

          <Section title="19. Third-Party Service Providers">
            <p>We share data with the following processors only to the extent necessary to operate the App:</p>
            <ul style={{ marginTop: 8, paddingLeft: 20, display: "flex", flexDirection: "column", gap: 6, listStyleType: "disc" }}>
              <li><span style={{ fontWeight: 600, color: "#374151" }}>Supabase</span>: secure database hosting and user authentication.</li>
              <li><span style={{ fontWeight: 600, color: "#374151" }}>Anthropic</span>: AI-powered meal photo analysis and nudge generation.</li>
              <li><span style={{ fontWeight: 600, color: "#374151" }}>OpenAI</span>: AI-powered meal photo analysis (used as a fallback provider).</li>
              <li><span style={{ fontWeight: 600, color: "#374151" }}>RevenueCat</span>: subscription and in-app purchase management.</li>
              <li><span style={{ fontWeight: 600, color: "#374151" }}>Vercel</span>: application hosting and infrastructure.</li>
              <li><span style={{ fontWeight: 600, color: "#374151" }}>Apple</span>: payment processing for App Store subscriptions.</li>
            </ul>
            <p>Each provider operates under its own privacy policy and data processing agreements. WhatYouAte is not responsible for the data practices of these third parties beyond the contractual safeguards in place.</p>
          </Section>

          <Section title="20. Data Retention and Deletion">
            <p>We retain your data for as long as your account is active. You may delete your account and all associated data at any time using the "Delete account" option in your Profile. Upon deletion, your personal data is removed from our systems within a reasonable period, except where retention is required by law.</p>
          </Section>

          <Section title="21. Security">
            <p>We use industry-standard security measures including encryption in transit (TLS) and encryption at rest to protect your data. No method of transmission over the internet is 100% secure. While we take reasonable steps to protect your information, we cannot guarantee absolute security.</p>
          </Section>

          <Section title="22. Your Rights">
            <p>Depending on your location, you may have rights including: the right to access your personal data; the right to correct inaccurate data; the right to request deletion; the right to data portability; and the right to withdraw consent.</p>
            <p>Canadian residents have rights under the Personal Information Protection and Electronic Documents Act (PIPEDA). Residents of the European Economic Area have rights under the General Data Protection Regulation (GDPR). Residents of California have rights under the California Consumer Privacy Act (CCPA), including the right to know what personal information is collected, the right to delete personal information, and the right to opt out of the sale of personal information (we do not sell personal information). To exercise any of these rights, contact us using the information below.</p>
          </Section>

          <Section title="23. International Users">
            <p>WhatYouAte is operated from Canada. If you access the App from outside Canada, your information may be transferred to and processed in Canada. By using the App, you consent to this transfer. We take steps to ensure that data transferred internationally receives an adequate level of protection.</p>
          </Section>

          <Section title="24. Cookies and Local Storage">
            <p>The App uses browser local storage to save preferences and cached data on your device. This data does not leave your device except as described in this policy. We do not use third-party tracking cookies or advertising trackers.</p>
          </Section>

          <Section title="25. Changes to This Policy">
            <p>We may update this policy as the App evolves. Material changes will be communicated within the App. The effective date at the top of this page reflects the most recent revision. Continued use of the App after changes are posted constitutes acceptance of the revised policy.</p>
          </Section>

          <Section title="26. Contact">
            <p>
              For privacy inquiries, data requests, or any questions about these terms, contact us at:{" "}
              <a href="mailto:hello@minimul.app" style={{ color: "#6FA8FF", textDecoration: "none" }}>
                hello@minimul.app
              </a>
            </p>
          </Section>

        </div>
      </div>
    </div>
  );
}
